default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: request_dumper_dev

production:
  <<: *default
  database: request_dumper_production
  username: request_dumper
  password: <%= ENV['REQUEST_DUMPER_DATABASE_PASSWORD'] %>
